### ISSUE TITLE
Incorrect number of seconds in a day

### ISSUE THREAD

**Issue by Pikamander2** [jertel/elastalert2#1436]
Hi there, I used a code search and found an incorrect number of seconds in a day (84600 instead of 86400) listed in one of your files. I recommend fixing it to avoid incorrect timings that could potentially lead to unexpected behavior.

https://github.com/jertel/elastalert2/blob/3b4608ca8f9c4b69153ecd6a44a42d7a70562ecc/docs/source/alerts.rst#L250

**Comment by jertel** [comment]
Thanks for raising the problem. While I agree it is a typo, the file you referenced is a documentation file, not a code file.

I've pushed a fix for the documentation.

This is a community contributed project. In the future, it would be more helpful to submit a corrective pull request, rather than opening issues and asking someone else to fix it.
