### ISSUE TITLE
Support for Arm architectures

### ISSUE THREAD

**Issue by rdomloge** [jertel/elastalert2#681]
I have a kubernetes cluster running ElasticSearch 7.14 and would really like to use ElastAlert2 to monitor it. It should be as simple as adjusting your build pipeline to build for multi architectures:

`docker buildx build --platform linux/amd64,linux/arm64 -t jertel/elastalert:2.3.1 . --push`

This command will take quite a bit longer, so not desirable during development iterations, just release.
I cloned the repo and ran it myself, and it seems to work fine.

**Comment by jertel** [comment]
This is implemented for Docker Hub only. Currently the `latest` tag has amd64 and arm64. armv7 is always problematic due to rust/crypto/cffi broken deps so I've opted to leave it out. If there's demand I may also push multi-arch up to the GitHub CR, but for now arm64 is only available on Docker Hub.
